name: Build, Test & Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure install-sh is executable
        run: |
          chmod +x dsniff-old/install-sh

      - name: Setup Python
        uses: actions/setup-python@v5  # Updated to latest version
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            autoconf \
            automake \
            libtool \
            libpcap-dev \
            libnet-dev \
            libnids-dev \
            libssl-dev \
            bison \
            flex

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution
        run: python -m build --sdist --wheel

      - name: Verify installation
        run: |
          pip install dist/*.whl
          pip list | grep dsniff

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --skip-existing dist/*